### ISSUE TITLE
ImportError with PyPi installation

### ISSUE THREAD

**Issue by whyayen** [KKBOX/kkbox_openapi_developer_sdk#4]
I used PyPi installation to install this sdk, but every module print ImportError.

I found out the error.
Every module import other class without '.' , but there are '.' before module name in the files on GitHub.

Detail:
* pip
```from fetcher import *``` 
* GitHub Repository
```from .fetcher import *```

Is it my problem or PyPi no update ?

**Comment by willyliu** [comment]
Sorry for late reply. 

We have updated the module on PyPi, please update your kkbox-developer-sdk module, thanks.
